[package]
name = "matching_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
slab = "0.4"
hashbrown = "0.14"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5"
rand = "0.8"
